### PR TITLE
Added terraqueous, ars_nouveau, Fruit Tree Support

### PR DESCRIPTION
**Pull request by ModernGamingWorld**
Closes this I think
https://github.com/Darkhax-Minecraft/BotanyPots/issues/94

### CODE REVIEW

**Comment by Darkhax** [comment]
Thanks for the PR. When adding non-vanilla support you need to include conditions that prevent the support from loading when the mod is not present. You can find an example of this [here](https://github.com/Darkhax-Minecraft/BotanyTrees/blob/1.16.4/src/main/resources/data/botanytrees/recipes/byg/baobab.json#L3-L12). I recommend adding two conditions, the first only loads the file when the mod ID specified has been loaded, the second only loads the file when a specific item is present. The item check is used to prevent errors if the mod decides to remove that item later on.

**Comment by ModernGamingWorld** [comment]
@Darkhax Fixed

**Comment by ModernGamingWorld** [comment]
These should be good to close after this pr is sent through to the Mod

https://github.com/Darkhax-Minecraft/BotanyTrees/issues/10
https://github.com/Darkhax-Minecraft/BotanyTrees/issues/13

**Comment by Darkhax** [comment]
Wow, that's a lot of trees. Thanks!

**Pull request merged**
