### PR TITLE
Add support for Regions Unexplored (1.18.2)

### PR DESCRIPTION
**Pull request by ChiefArug**
Partially solves https://github.com/Darkhax-Minecraft/BotanyPots/issues/339 (still need to do stuff for BotanyPots itself)

Note that this likely cannot just be cherry picked to 1.20.1+ due to the mod having a big rewrite. I will test on that and other versions and update here (and make a new PR if needed).

### CODE REVIEW

**Comment by ChiefArug** [comment]
Tested and works on 1.19.2 if cherrypicked there.

**Comment by Darkhax** [comment]
Nice, is this still a draft?

**Comment by ChiefArug** [comment]
I believe this is done for 1.18.2, and can be cherry picked to 1.19.2 too. 1.20 likely not due to large changes in the mod.
The Botany Pots PR still needs some work and should still be a draft (may not be able to work on it for a couple of days though).

**Comment by Darkhax** [comment]
Sorry this took so long to review, thanks for the help.

**Pull request merged**
